using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AlSuitBuilder.Shared
{


	public static partial class Dictionaries
	{

		public static Dictionary<int, string> MaterialInfo = new Dictionary<int, string>
		{
			{ 1, "Ceramic" },
			{ 2, "Porcelain" },
			// 3
			{ 4, "Linen" },
			{ 5, "Satin" },
			{ 6, "Silk" },
			{ 7, "Velvet" },
			{ 8, "Wool" },
			// 9
			{ 10, "Agate" },
			{ 11, "Amber" },
			{ 12, "Amethyst" },
			{ 13, "Aquamarine" },
			{ 14, "Azurite" },
			{ 15, "Black Garnet" },
			{ 16, "Black Opal" },
			{ 17, "Bloodstone" },
			{ 18, "Carnelian" },
			{ 19, "Citrine" },
			{ 20, "Diamond" },
			{ 21, "Emerald" },
			{ 22, "Fire Opal" },
			{ 23, "Green Garnet" },
			{ 24, "Green Jade" },
			{ 25, "Hematite" },
			{ 26, "Imperial Topaz" },
			{ 27, "Jet" },
			{ 28, "Lapis Lazuli" },
			{ 29, "Lavender Jade" },
			{ 30, "Malachite" },
			{ 31, "Moonstone" },
			{ 32, "Onyx" },
			{ 33, "Opal" },
			{ 34, "Peridot" },
			{ 35, "Red Garnet" },
			{ 36, "Red Jade" },
			{ 37, "Rose Quartz" },
			{ 38, "Ruby" },
			{ 39, "Sapphire" },
			{ 40, "Smokey Quartz" },
			{ 41, "Sunstone" },
			{ 42, "Tiger Eye" },
			{ 43, "Tourmaline" },
			{ 44, "Turquoise" },
			{ 45, "White Jade" },
			{ 46, "White Quartz" },
			{ 47, "White Sapphire" },
			{ 48, "Yellow Garnet" },
			{ 49, "Yellow Topaz" },
			{ 50, "Zircon" },
			{ 51, "Ivory" },
			{ 52, "Leather" },
			{ 53, "Armoredillo Hide" },
			{ 54, "Gromnie Hide" },
			{ 55, "Reed Shark Hide" },
			// 56
			{ 57, "Brass" },
			{ 58, "Bronze" },
			{ 59, "Copper" },
			{ 60, "Gold" },
			{ 61, "Iron" },
			{ 62, "Pyreal" },
			{ 63, "Silver" },
			{ 64, "Steel" },
			// 65
			{ 66, "Alabaster" },
			{ 67, "Granite" },
			{ 68, "Marble" },
			{ 69, "Obsidian" },
			{ 70, "Sandstone" },
			{ 71, "Serpentine" },
			{ 73, "Ebony" },
			{ 74, "Mahogany" },
			{ 75, "Oak" },
			{ 76, "Pine" },
			{ 77, "Teak" },
		};

		public static Dictionary<int, string> SetInfo = new Dictionary<int, string>
		{
			// This list was taken from Virindi Tank Loot Editor
			// 01
			{ 02, "Test"},
			// 03
			{ 04, "Carraida's Benediction"},
			{ 05, "Noble Relic Set" },
			{ 06, "Ancient Relic Set" },
			{ 07, "Relic Alduressa Set" },
			{ 08, "Shou-jen Set" },
			{ 09, "Empyrean Rings Set" },
			{ 10, "Arm, Mind, Heart Set" },
			{ 11, "Coat of the Perfect Light Set" },
			{ 12, "Leggings of Perfect Light Set" },
			{ 13, "Soldier's Set" },
			{ 14, "Adept's Set" },
			{ 15, "Archer's Set" },
			{ 16, "Defender's Set" },
			{ 17, "Tinker's Set" },
			{ 18, "Crafter's Set" },
			{ 19, "Hearty Set" },
			{ 20, "Dexterous Set" },
			{ 21, "Wise Set" },
			{ 22, "Swift Set" },
			{ 23, "Hardenend Set" },
			{ 24, "Reinforced Set" },
			{ 25, "Interlocking Set" },
			{ 26, "Flame Proof Set" },
			{ 27, "Acid Proof Set" },
			{ 28, "Cold Proof Set" },
			{ 29, "Lightning Proof Set" },
			{ 30, "Dedication Set" },
			{ 31, "Gladiatorial Clothing Set" },
			{ 32, "Ceremonial Clothing" },
			{ 33, "Protective Clothing" },
			{ 34, "Noobie Armor" },
			{ 35, "Sigil of Defense" },
			{ 36, "Sigil of Destruction" },
			{ 37, "Sigil of Fury" },
			{ 38, "Sigil of Growth" },
			{ 39, "Sigil of Vigor" },
			{ 40, "Heroic Protector Set" },
			{ 41, "Heroic Destroyer Set" },
			{ 42, "Olthoi Armor D Red" },
			{ 43, "Olthoi Armor C Rat" },
			{ 44, "Olthoi Armor C Red" },
			{ 45, "Olthoi Armor D Rat" },
			{ 46, "Upgraded Relic Alduressa Set" },
			{ 47, "Upgraded Ancient Relic Set" },
			{ 48, "Upgraded Noble Relic Set" },
			{ 49, "Weave of Alchemy" },
			{ 50, "Weave of Arcane Lore" },
			{ 51, "Weave of Armor Tinkering" },
			{ 52, "Weave of Assess Person" },
			{ 53, "Weave of Light Weapons" },
			{ 54, "Weave of Missile Weapons" },
			{ 55, "Weave of Cooking" },
			{ 56, "Weave of Creature Enchantment" },
			{ 57, "Weave of Missile Weapons" },
			{ 58, "Weave of Finesse" },
			{ 59, "Weave of Deception" },
			{ 60, "Weave of Fletching" },
			{ 61, "Weave of Healing" },
			{ 62, "Weave of Item Enchantment" },
			{ 63, "Weave of Item Tinkering" },
			{ 64, "Weave of Leadership" },
			{ 65, "Weave of Life Magic" },
			{ 66, "Weave of Loyalty" },
			{ 67, "Weave of Light Weapons" },
			{ 68, "Weave of Magic Defense" },
			{ 69, "Weave of Magic Item Tinkering" },
			{ 70, "Weave of Mana Conversion" },
			{ 71, "Weave of Melee Defense" },
			{ 72, "Weave of Missile Defense" },
			{ 73, "Weave of Salvaging" },
			{ 74, "Weave of Light Weapons" },
			{ 75, "Weave of Light Weapons" },
			{ 76, "Weave of Heavy Weapons" },
			{ 77, "Weave of Missile Weapons" },
			{ 78, "Weave of Two Handed Combat" },
			{ 79, "Weave of Light Weapons" },
			{ 80, "Weave of Void Magic" },
			{ 81, "Weave of War Magic" },
			{ 82, "Weave of Weapon Tinkering" },
			{ 83, "Weave of Assess Creature " },
			{ 84, "Weave of Dirty Fighting" },
			{ 85, "Weave of Dual Wield" },
			{ 86, "Weave of Recklessness" },
			{ 87, "Weave of Shield" },
			{ 88, "Weave of Sneak Attack" },
			{ 89, "Ninja_New" },
			{ 90, "Weave of Summoning" },

			{ 91, "Shrouded Soul" },
			{ 92, "Darkened Mind" },
			{ 93, "Clouded Spirit" },
			{ 94, "Minor Stinging Shrouded Soul" },
			{ 95, "Minor Sparking Shrouded Soul" },
			{ 96, "Minor Smoldering Shrouded Soul" },
			{ 97, "Minor Shivering Shrouded Soul" },
			{ 98, "Minor Stinging Darkened Mind" },
			{ 99, "Minor Sparking Darkened Mind" },

			{ 100, "Minor Smoldering Darkened Mind" },
			{ 101, "Minor Shivering Darkened Mind" },
			{ 102, "Minor Stinging Clouded Spirit" },
			{ 103, "Minor Sparking Clouded Spirit" },
			{ 104, "Minor Smoldering Clouded Spirit" },
			{ 105, "Minor Shivering Clouded Spirit" },
			{ 106, "Major Stinging Shrouded Soul" },
			{ 107, "Major Sparking Shrouded Soul" },
			{ 108, "Major Smoldering Shrouded Soul" },
			{ 109, "Major Shivering Shrouded Soul" },

			{ 110, "Major Stinging Darkened Mind" },
			{ 111, "Major Sparking Darkened Mind" },
			{ 112, "Major Smoldering Darkened Mind" },
			{ 113, "Major Shivering Darkened Mind" },
			{ 114, "Major Stinging Clouded Spirit" },
			{ 115, "Major Sparking Clouded Spirit" },
			{ 116, "Major Smoldering Clouded Spirit" },
			{ 117, "Major Shivering Clouded Spirit" },
			{ 118, "Blackfire Stinging Shrouded Soul" },
			{ 119, "Blackfire Sparking Shrouded Soul" },

			{ 120, "Blackfire Smoldering Shrouded Soul" },
			{ 121, "Blackfire Shivering Shrouded Soul" },
			{ 122, "Blackfire Stinging Darkened Mind" },
			{ 123, "Blackfire Sparking Darkened Mind" },
			{ 124, "Blackfire Smoldering Darkened Mind" },
			{ 125, "Blackfire Shivering Darkened Mind" },
			{ 126, "Blackfire Stinging Clouded Spirit" },
			{ 127, "Blackfire Sparking Clouded Spirit" },
			{ 128, "Blackfire Smoldering Clouded Spirit" },
			{ 129, "Blackfire Shivering Clouded Spirit" },

			{ 130, "Shimmering Shadows" },

			{ 131, "Brown Society Locket" },
			{ 132, "Yellow Society Locket" },
			{ 133, "Red Society Band" },
			{ 134, "Green Society Band" },
			{ 135, "Purple Society Band" },
			{ 136, "Blue Society Band" },

			{ 137, "Gauntlet Garb" },

			{ 138, "UNKNOWN_138" }, // Possibly Paragon Missile Weapons
			{ 139, "UNKNOWN_139" }, // Possibly Paragon Casters
			{ 140, "UNKNOWN_140" }, // Possibly Paragon Melee Weapons
		};
	}
}
